theme: null
markdown: kramdown
plugins: []
title: KNODIS research group
author: KNODIS
email: gi.knodis@upm.es
url: https://knodis-research-group.github.io/
description: KNOwledge Discovery & Information Systems research group  
favicon: "knodis-logo_minimo.png"
